services:
  spring-app:
    build: .
    ports:
      - "3003:3003"  # host:container
    container_name: springboot-app
    restart: unless-stopped
  garage-sim:
    image: cfontes0estapar/garage-sim:1.0.0
    network_mode: "host"
    restart: unless-stopped
    container_name: garage-sim
  garage-sim2:
    ports:
      - "3001:3001"
    image: cfontes0estapar/garage-sim:1.0.0
    network_mode: "host"
    restart: unless-stopped
    container_name: garage-sim2
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=gestacar'
      - 'POSTGRES_PASSWORD=s3cr3t'
      - 'POSTGRES_USER=gestacaruser'
    ports:
      - '5432:5432'
